apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s/grafana/
    serve_from_sub_path = true

    [auth.anonymous]
    enabled = true
    org_role = Viewer

    [security]
    admin_user = admin
    
    [users]
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Editor
