apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
data:
  # Default password is "admin" - you should change this in production
  admin-password: YWRtaW4=  # base64 encoded "admin"
